[build]
  command = "pnpm install && pnpm --filter web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "8"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "apps/web/.netlify/functions" 