# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd773146a4815ca8329d785bee797aeb"
name = "Heard-Test"
handle = "heard-test"
application_url = "https://heard.amindaily.me"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "heard-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://heard.amindaily.me/auth"
]

[pos]
embedded = false
